In [ ]:
import pandas as pd

In [ ]:
disc = pd.read_csv("datasets/discussion.csv")
prob = pd.read_csv("datasets/problemset.csv")
print(disc.shape)

In [ ]:
first_tier = disc.loc[disc['Parent_Id']==0, :]
second_tier = disc.loc[disc['Parent_Id']!=0, :]
print(first_tier.shape)
print(second_tier.shape)

In [ ]:
first_tier_sample = first_tier.sample(500)
second_tier_sample = second_tier.sample(500)

### Creez primul sample de adnotari

In [ ]:
# sentences = pd.DataFrame([prob.loc[prob['Problem Name']==text, 'Description'] for text in first_tier_sample['Problem Name']])
first_tier_sample = first_tier_sample.merge(prob[['Problem Name', 'Description']], on='Problem Name', how='left')

In [ ]:
print(first_tier_sample.head(n=4))
first_tier_sample.to_csv('annotations/first_tier_sample.csv')

### Creez al doilea set de adnotari

In [ ]:
print(second_tier_sample.index)  # Verifică indexul lui second_tier_sample
print(disc.index)  # Verifică indexul lui disc
second_tier_sample.reset_index(drop=True, inplace=True)
disc.reset_index(drop=True, inplace=True)

In [ ]:
second_tier_sample['Parent Text'] = disc.loc[
    (disc['Id'] == second_tier_sample['Parent_Id']) &
    (disc['Problem Name'] == second_tier_sample['Problem Name']),
    'Text'
]
second_tier_sample.head(n=4)
# merged = second_tier.merge(disc, left_on=['Parent_Id', 'Problem Name'], right_on=['Id', 'Problem Name'], how='left')
# merged.head(n=10)

In [34]:
second_tier_sample = second_tier_sample.merge(
    disc[['Id', 'Problem Name', 'Text']],
    left_on=['Parent_Id', 'Problem Name'],
    right_on=['Id', 'Problem Name'],
    how='inner'
)
# second_tier_sample.head(n=10)

In [41]:
second_tier_sample.drop(columns=['Parent_Text'], inplace=True)
second_tier_sample.rename(columns={'Text_y':'Parent Text'}, inplace=True)
second_tier_sample.drop(columns=['Id_y'], inplace=True)

,Problem Name,Id_x,Parent_Id,Text_x,Date,Up Votes,Username,Parent_Up_Votes,Parent_Date,Parent Text
0,minimum-moves-to-capture-the-queen\n,66,62,same :( i spent my entire time even after the ...,"Jan 07, 2024",0,ritzo37,NaN,NaN,I tried to do it by recusrion anyone else I th...
1,find-the-student-that-will-replace-the-chalk\n,50,48,@zaskyou well then you'll have to wait,"Sep 03, 2024",0,jshim2705,NaN,NaN,Is there a mistake in Hint 2?Hint 1: Subtract ...
2,managers-with-at-least-5-direct-reports\n,6,1,What is the problem with this ?\nselect name\n...,"May 15, 2024",0,appie_pie,NaN,NaN,Easiest with the right logic\nI never understo...
3,minimum-cost-to-convert-string-i\n,159,158,@neks yess actually true,"Jul 27, 2024",0,ShreyaGarg63,NaN,NaN,Graphs and trees are the most difficult ones 😭😭
4,frequency-of-the-most-frequent-element\n,147,146,@yao0103 any idea why ?\ncause its not the lar...,"Feb 04, 2024",0,balajirai,NaN,NaN,NaN
5,array-prototype-last\n,37,35,Why would a programming exercise need to confo...,"May 27, 2023",0,tifv,NaN,NaN,the Array.at() method has already shipped and ...
6,move-zeroes\n,216,214,@d75324 the line 17 : nums = nums + [0]*num_ze...,"Nov 06, 2023",0,suraj479,16,"Oct 28, 2024",Can anyone tell me what is wrong with my code ...
7,rank-transform-of-an-array\n,19,15,thanks case bro,"Oct 02, 2024",4,Garv_Virmani,NaN,NaN,TESTCASES--------------->
8,exclusive-time-of-functions\n,21,19,I think the expected result is incorrect. I ha...,"May 03, 2024",0,arabisoft,NaN,NaN,"case 120\nn = 3, logs = [""1:start:0"",""0:start:..."
9,game-play-analysis-iv\n,38,33,"have you tried adding IFNULL ( ,0) to the form...","May 17, 2023",0,Panda_30,NaN,NaN,Got stuck with this question. My code can pass...

In [50]:
merged = second_tier_sample.merge(
    disc[['Id', 'Problem Name', 'Up Votes']],
    left_on=['Parent_Id', 'Problem Name'],
    right_on=['Id', 'Problem Name'],
    how='left'
)
second_tier_sample['Parent_Up_Votes'] = merged['Up Votes_y']

In [51]:
merged = second_tier_sample.merge(
    disc[['Id', 'Problem Name', 'Date']],
    left_on=['Parent_Id', 'Problem Name'],
    right_on=['Id', 'Problem Name'],
    how='left'
)
second_tier_sample['Parent_Date'] = merged['Date_y']

In [52]:
second_tier_sample.head(n=10)

,Problem Name,Id_x,Parent_Id,Text_x,Date,Up Votes,Username,Parent_Up_Votes,Parent_Date,Parent Text
0,minimum-moves-to-capture-the-queen\n,66,62,same :( i spent my entire time even after the ...,"Jan 07, 2024",0,ritzo37,0,"Jan 07, 2024",I tried to do it by recusrion anyone else I th...
1,find-the-student-that-will-replace-the-chalk\n,50,48,@zaskyou well then you'll have to wait,"Sep 03, 2024",0,jshim2705,6,"Sep 02, 2024",Is there a mistake in Hint 2?Hint 1: Subtract ...
2,managers-with-at-least-5-direct-reports\n,6,1,What is the problem with this ?\nselect name\n...,"May 15, 2024",0,appie_pie,88,"May 11, 2023",Easiest with the right logic\nI never understo...
3,minimum-cost-to-convert-string-i\n,159,158,@neks yess actually true,"Jul 27, 2024",0,ShreyaGarg63,0,"Jul 27, 2024",Graphs and trees are the most difficult ones 😭😭
4,frequency-of-the-most-frequent-element\n,147,146,@yao0103 any idea why ?\ncause its not the lar...,"Feb 04, 2024",0,balajirai,0,"Feb 04, 2024",NaN
5,array-prototype-last\n,37,35,Why would a programming exercise need to confo...,"May 27, 2023",0,tifv,1,"May 27, 2023",the Array.at() method has already shipped and ...
6,move-zeroes\n,216,214,@d75324 the line 17 : nums = nums + [0]*num_ze...,"Nov 06, 2023",0,suraj479,0,"Nov 06, 2023",Can anyone tell me what is wrong with my code ...
7,rank-transform-of-an-array\n,19,15,thanks case bro,"Oct 02, 2024",4,Garv_Virmani,32,"Oct 02, 2024",TESTCASES--------------->
8,exclusive-time-of-functions\n,21,19,I think the expected result is incorrect. I ha...,"May 03, 2024",0,arabisoft,11,"Apr 13, 2024","case 120\nn = 3, logs = [""1:start:0"",""0:start:..."
9,game-play-analysis-iv\n,38,33,"have you tried adding IFNULL ( ,0) to the form...","May 17, 2023",0,Panda_30,9,"Mar 03, 2021",Got stuck with this question. My code can pass...

In [53]:
second_tier_sample.to_csv('annotations/second_tier_sample.csv')